// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnz3v0yDDSpPyoa8Ea8u7iagiqT75AlCY',
    appId: '1:877713775382:web:ca14f8b7f20a57f28b4e37',
    messagingSenderId: '877713775382',
    projectId: 'skiddy',
    authDomain: 'skiddy.firebaseapp.com',
    databaseURL: 'https://skiddy.firebaseio.com',
    storageBucket: 'skiddy.appspot.com',
    measurementId: 'G-7GYG8ZLCJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUis6OgphM1kQKprM58C2tO7IX_v7B7Y4',
    appId: '1:877713775382:android:84d3614b7afded6a8b4e37',
    messagingSenderId: '877713775382',
    projectId: 'skiddy',
    databaseURL: 'https://skiddy.firebaseio.com',
    storageBucket: 'skiddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJGxUXCsjFgDAo46J7Uhddyib2zzfjFg4',
    appId: '1:877713775382:ios:dea612b9c8049a348b4e37',
    messagingSenderId: '877713775382',
    projectId: 'skiddy',
    databaseURL: 'https://skiddy.firebaseio.com',
    storageBucket: 'skiddy.appspot.com',
    iosClientId: '877713775382-4bdbnaq9mnm32d8afvi2leual1h75fv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.housingsociety',
  );
}
