// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtqBGet4ei5a9bcEhjU_Oiye_AxiCIqTQ',
    appId: '1:411194630020:web:964a544e5aa6db7599c7d1',
    messagingSenderId: '411194630020',
    projectId: 'housingsociety786',
    authDomain: 'housingsociety786.firebaseapp.com',
    storageBucket: 'housingsociety786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSfgAGVhR5ApNLl27UrStyZ2T6js0DAk',
    appId: '1:411194630020:android:ee990a0a8172d33199c7d1',
    messagingSenderId: '411194630020',
    projectId: 'housingsociety786',
    storageBucket: 'housingsociety786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfdX5uKXTt7_w2NaNTR2dJwq0nPL9_-9g',
    appId: '1:411194630020:ios:c7db1c1850f0c3b399c7d1',
    messagingSenderId: '411194630020',
    projectId: 'housingsociety786',
    storageBucket: 'housingsociety786.appspot.com',
    iosClientId: '411194630020-otvjelfc7tpcphm13loa13io36a0rvgb.apps.googleusercontent.com',
    iosBundleId: 'co',
  );
}
